<?php
//When using sessions you must declare session_start() at the start of each php file that you use $_SESSSION
session_start();
//This is the superglobal variable $_SESSION with a variable 'login' with the value 'webmaster'
$_SESSION["login"] = "webmaster";
//Display the session/login variable
echo $_SESSION["login"];//displays 'webmaster'
echo "<br>";


//Each session has a unique id generated by php
//The function session_id returns the id

//session_start();

$_SESSION["login"] = "webmaster";
$_SESSION["role"] = "admin";

echo "- session ID : " . session_id();//displays '- session ID : m3hefgke6itvvs6sbqka0f55jk
echo "<br>";

//This ID is stored as a cookie client-side and as a file on the server.
//When there is an exchange of data, the server compares the files to check that the id is identical


//session_start();

if (!isset($_SESSION["login"])) {
    header("Location:index.php");
    exit;
}

// Reste du code (PHP/HTML)
echo "Bonjour " . $_SESSION["login"] . "<br>"; //displays 'Bonjour webmaster'
echo "<br>";




//The session name is not to be confused with the session id
//By default it is 'PHPSESSID'
//session_start();
echo"- Nom de la session : ".session_name(); //displays '- Nom de la session : PHPSESSID'
echo "<br>";

//You can name the session but only at the beginning.
//Once the session is active it is not possible to change the name.
//The following code will generate an error due to the code above having made the session active
//session_start();
session_name("afpa");
echo"- Nom de la session : ".session_name(); //displays '- Nom de la session : afpa'





//To properly destroy a session
$_SESSION["login"] = "";//assign an empty value to the session variables
$_SESSION["role"] = "";//assign an empty value to the session variables

unset($_SESSION["login"]);//delete the session variable
unset($_SESSION["role"]);//delete the session variable

if (ini_get("session.use_cookies"))
{
    setcookie(session_name(), '', time()-1); //delete the cookie relating to the session
}

session_destroy();


